sudo: required
services:
  - docker

before_install:
  - docker build -t renatoaraujo/docker-deploy -f Dockerfile.dev .

script:
  - docker run -e CI=true renatoaraujo/docker-deploy npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-deploy"
  env: "Docker-deploy-env"
  bucket_name: "elasticbeanstalk-eu-north-1-706467675800"
  bucket_path: "docker-deploy"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
